# backend/models_config.py

MODELS = {
    "qwen2.5-72b": {
        "display_name": "Qwen2.5-72B",
        "qwen_model_id": "Qwen/Qwen2.5-72B-Instruct",
        "accuracy": 9,
        "speed": 5,
        "cost_efficiency": 5,
        "privacy": 4,
        "best_tasks": ["reasoning", "rag", "creative"],
        "latency_tier": 4,
        "cost_per_1k": 0.04,
    },
    "qwen2.5-32b": {
        "display_name": "Qwen2.5-32B",
        "qwen_model_id": "Qwen/Qwen2.5-32B-Instruct",
        "accuracy": 8,
        "speed": 7,
        "cost_efficiency": 7,
        "privacy": 4,
        "best_tasks": ["rag", "summarize", "reasoning"],
        "latency_tier": 3,
        "cost_per_1k": 0.015,
    },
    "qwen2.5-14b": {
        "display_name": "Qwen2.5-14B",
        "qwen_model_id": "Qwen/Qwen2.5-14B-Instruct",
        "accuracy": 7,
        "speed": 8,
        "cost_efficiency": 8,
        "privacy": 4,
        "best_tasks": ["rag", "summarize", "creative"],
        "latency_tier": 2,
        "cost_per_1k": 0.006,
    },
    "qwen2.5-7b": {
        "display_name": "Qwen2.5-7B",
        "qwen_model_id": "Qwen/Qwen2.5-7B-Instruct",
        "accuracy": 6,
        "speed": 10,
        "cost_efficiency": 10,
        "privacy": 4,
        "best_tasks": ["summarize", "creative", "code"],
        "latency_tier": 1,
        "cost_per_1k": 0.002,
    },
    "qwen2.5-coder-32b": {
        "display_name": "Qwen2.5-Coder-32B",
        "qwen_model_id": "Qwen/Qwen2.5-Coder-32B-Instruct",
        "accuracy": 9,
        "speed": 6,
        "cost_efficiency": 7,
        "privacy": 4,
        "best_tasks": ["code"],
        "latency_tier": 3,
        "cost_per_1k": 0.01,
    },
}
